import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    overlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.35)',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 20,
        position: 'fixed',
        borderRadius: 24,
         
    },
    popup: {
        backgroundColor: 'white',
        borderRadius: 24,
        width: '100%',
        maxWidth: 420,
        minHeight: 700,
        maxHeight: '90%',
        shadowColor: 'rgba(0, 0, 0, 0.3)',
        shadowOffset: { width: 0, height: 20 },
        shadowOpacity: 0.3,
        shadowRadius: 25,
        elevation: 20,
        flexDirection: 'column',
        flex: 1,
        overflow: 'hidden',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 24,
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#f1f5f9',
        backgroundColor: '#fafafa',
    },
    title: {
        fontSize: 20,
        fontWeight: '700',
        color: '#1e293b',
        flex: 1,
        letterSpacing: 0.5,
    },
    closeButton: {
        minWidth: 36,
        minHeight: 36,
        marginVertical: 0,
        marginHorizontal: 0,
        marginLeft: 12,
        backgroundColor: 'transparent',
        borderRadius: 18,
        shadowOpacity: 0,
        elevation: 0,
    },
    closeButtonText: {
        fontSize: 16,
        fontWeight: 'bold',
    },
    content: {
        flex: 1,
        padding: 20,
        paddingTop: 16,
    },
    inputContainer: {
        marginBottom: 20,
    },
    label: {
        fontSize: 15,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 8,
        letterSpacing: 0.3,
    },
    required: {
        color: '#ef4444',
        fontWeight: '700',
    },
    input: {
        borderWidth: 1.5,
        borderColor: '#d1d5db',
        borderRadius: 16,
        padding: 16,
        fontSize: 16,
        backgroundColor: '#fafafa',
        color: '#374151',
        shadowColor: 'rgba(0, 0, 0, 0.05)',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
        fontWeight: '500',
        // Focus state enhancement
        '&:focus': {
            borderColor: '#2563eb',
            backgroundColor: '#ffffff',
        },
    },
    footer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: '#f1f5f9',
        backgroundColor: '#fafafa',
        gap: 10,
        maxWidth: 200,
    },
    selectedItemInfo: {
        backgroundColor: '#f0fdf4',
        padding: 16,
        borderRadius: 16,
        marginBottom: 20,
        borderLeftWidth: 4,
        borderLeftColor: '#10b981',
        shadowColor: 'rgba(16, 185, 129, 0.1)',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    selectedItemText: {
        color: '#065f46',
        fontWeight: '600',
        fontSize: 14,
        letterSpacing: 0.3,
    },
    labelWithIcon: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 6,
    },
    labelIcon: {
        marginRight: 8,
        marginBottom: 0,
        opacity: 0.7,
    },
    inputWrapper: {
        position: 'relative',
    },
    dropdown: {
        position: 'absolute',
        top: '100%',
        left: 0,
        right: 0,
        backgroundColor: 'white',
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 16,
        maxHeight: 180,
        zIndex: 1000,
        elevation: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.15,
        shadowRadius: 12,
        marginTop: 4,
    },
    dropdownList: {
        maxHeight: 180,
        borderRadius: 16,
    },
    dropdownItem: {
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#f3f4f6',
        backgroundColor: 'white',
        // Hover effect simulation
        activeOpacity: 0.7,
    },
    dropdownItemName: {
        fontSize: 15,
        fontWeight: '600',
        color: '#374151',
        letterSpacing: 0.3,
    },
    dropdownItemDetails: {
        fontSize: 13,
        color: '#6b7280',
        marginTop: 4,
        fontWeight: '500',
    },
    editablePrice: {
        borderColor: '#10b981',
        borderWidth: 2,
        backgroundColor: '#ffffff',
        shadowColor: 'rgba(16, 185, 129, 0.2)',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
    },
    priceHint: {
        fontSize: 12,
        color: '#10b981',
        fontStyle: 'italic',
        marginTop: 6,
        fontWeight: '500',
        letterSpacing: 0.2,
    },
    selectedItemSubText: {
        fontSize: 13,
        color: '#6b7280',
        marginTop: 4,
        fontWeight: '500',
    },
});

export default styles;